import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/Component/Provider";
import Navbar from "@/Component/Navbar";
import { Toaster } from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <Providers>
            <div className="fixed" 
                 style={{
                     top: 0,
                     left: 0,
                     right: 0,
                     height: "var(--geist-sans-font-size)",
                     backgroundColor: "var(--geist-background)",
                     zIndex: 1000,
                 }}>
                    <Navbar />
            </div>
            <br />
            <br />
            <br />
            <Toaster position="top-center" className="z-1950" richColors />
            {children} 
        </Providers>
        </body>
        </html>
    );
}